plan:
#	terraform plan -var-file staging.tfvars
#	terraform plan  -refresh=false
	terraform plan

apply:
#	terraform apply -var-file staging.tfvars -auto-approve  -refresh=false
#	terraform apply  -auto-approve  -refresh=false
	terraform apply  -auto-approve
